title: yojimbo87
description: Bits and bites of subjectively important information.
logo: "/assets/images/yojimbo87.png"
theme: just-the-docs

url: yojimbo87.github.io
favicon_ico: "/assets/images/favicon.png"
color_scheme: custom
destination: docs/